### ISSUE TITLE
Returns classes that are no longer annotated.

### ISSUE THREAD

**Issue by legaciespanda** [atteo/classindex#75] opened 2023-03-24 00:43 UTC
I created a custom java annotation to be used on my classes. I used classindex to retrieve all the classes using my custom annotation. which works pretty fine.

The problem is, when i remove the custom annotation from those classes, **classindex** library still retrieves the list of classes i removed the annotations from. Returns classes that are no longer annotated.

I think it's some sort of a cache from **classindex**. Can it be disabled?

**Comment by sentinelt** [comment] 2023-05-31 16:27
Duplicate of #54

**Closed as not planned by sentinelt** 2023-05-31 16:27 UTC
