### ISSUE TITLE
unable to get groovy classes annotated with @IndexAnnotated

### ISSUE THREAD

**Issue by yugantshah** [atteo/classindex#41] opened 2018-02-17 07:28 UTC
ClassFilter.only().topLevel().from(ClassIndex.getAnnotated(<Annotation>.class)) does not get groovy classes

**Comment by sentinelt** [comment] 2018-02-21 14:47
As I am not a Groovy user it is hard for me to reproduce the problem. Would you be so kind to provide me with a sample Groovy project which shows the problem?

Then I will be able to pinpoint the cause of the issue.

**Comment by sentinelt** [comment] 2022-11-25 00:49
Closing for now, if it is still an issue please provide a minimal example to reproduce it.

**Closed by sentinelt** 2022-11-25 00:49 UTC
